### ISSUE TITLE
Basic kit - Electronics

### ISSUE THREAD

**Issue by rhagman** [rhagman/sustainable-green-plants#6]
As a developer, I would like to build the electronics part of the basic kit.

Suggestion: Document in the wiki where to buy and how-to build the electronics part of the Basic kit.

**Comment by rhagman** [comment]
Almost done with the documentation in the [wiki](https://github.com/rhagman/sustainable-green-plants/wiki/Small-and-modular-DIY-kit). I realized that I ordered the wrong "pcb terminal block", so I need to update that part in the wiki. The how-to is done at [imgur](http://imgur.com/a/wkV9c). After updating the wiki with the correct "pcb terminal block" link and some tool updates that I found when I was building the thing, I can then close this issue.

**Comment by averageanomaly** [comment]
Hey! I was hoping to find where you got your pcb board. Your project looks great!

**Comment by mattiasr** [comment]
A co-worker helped design and printed with https://www.itead.cc

**Comment by rhagman** [comment]
You can find the pcb file here: https://github.com/rhagman/sustainable-green-plants/tree/master/pcb/2ch_12v_driver and then upload it to the site @mattiasr mentioned.
